services:
  - type: web
    name: fullstack-app
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build
      mv frontend/dist app/static
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
